// doctorSeeder.js

console.log(">>> RUNNING doctorSeeder.js");

const db = require("../config/mainConfig");      // your Sequelize instance
const Doctor = require("../Models/Attendee");     // your Doctor model

async function seedDoctors() {
  try {
    await db.authenticate();
    console.log("Connected to MariaDB for seeding");
    await Doctor.sync();

    // Uneven specialty distribution (more Family/Internal)
    const specialtyPool = [
      "Family Medicine", "Family Medicine", "Family Medicine", "Family Medicine",
      "Internal Medicine", "Internal Medicine", "Internal Medicine",
      "Cardiology", "Cardiology",
      "Orthopedics",
      "Neurology",
      "Dermatology",
      "Emergency Medicine",
    ];

    // 200 realistic-ish names (generated by combining lists)
    const firstNames = [
      "Ava","Noah","Emma","Liam","Olivia","Elijah","Sophia","Lucas","Mia","Mason",
      "Charlotte","Ethan","Amelia","James","Isabella","Benjamin","Harper","Leo","Evelyn","Henry",
      "Abigail","Jack","Ella","Sebastian","Scarlett","Alexander","Grace","Daniel","Chloe","Matthew",
      "Lily","Owen","Aria","Wyatt","Layla","Carter","Nora","Jayden","Riley","Dylan",
      "Zoey","Luke","Hannah","Gabriel","Addison","Isaac","Aubrey","Julian","Stella","Anthony",
      "Leah","Grayson","Samantha","David","Mila","Joseph","Lucy","Samuel","Paisley","Andrew",
      "Violet","John","Aurora","Christopher","Penelope","Joshua","Ellie","Nathan","Hazel","Caleb",
      "Emilia","Ryan","Madison","Asher","Kinsley","Thomas","Sofia","Charles","Ruby","Hunter",
      "Aaliyah","Christian","Ivy","Jonathan","Clara","Aaron","Naomi","Connor","Elena","Adrian",
      "Maya","Colton","Sarah","Nicholas","Skylar","Jeremiah","Jade","Jordan","Serenity","Evan",
    ];

    const lastNames = [
      "Patel","Nguyen","Singh","Chen","Wong","Brown","Smith","Johnson","Williams","Jones",
      "Garcia","Miller","Davis","Rodriguez","Martinez","Hernandez","Lopez","Gonzalez","Wilson","Anderson",
      "Thomas","Taylor","Moore","Jackson","Martin","Lee","Perez","Thompson","White","Harris",
      "Sanchez","Clark","Ramirez","Lewis","Robinson","Walker","Young","Allen","King","Wright",
      "Scott","Torres","Hill","Flores","Green","Adams","Nelson","Baker","Hall","Rivera",
      "Campbell","Mitchell","Carter","Roberts","Gomez","Phillips","Evans","Turner","Diaz","Parker",
      "Cruz","Edwards","Collins","Reyes","Stewart","Morris","Morales","Murphy","Cook","Rogers",
      "Gutierrez","Ortiz","Morgan","Cooper","Peterson","Bailey","Reed","Kelly","Howard","Ramos",
      "Kim","Shah","Khan","Ali","Hassan","Ibrahim","Chaudhry","Hussain","Ahmed","Das",
    ];

    const areaCodes = ["416", "647", "437", "905", "289", "519", "613"];

    const doctors = [];

    // IMPORTANT:
    // - scanSeeder cycles attendeeId 1–200, so we create EXACT ids 1–200.
    // - IDs 1–125 registered to Event 15, IDs 126–200 registered to Event 16.
    // Columns:
    // - physician: uneven (more true in Event15)
    // - checkedIn: uneven (higher check-in in Event15)
    // - npi: nullable; only set for some physicians (simulates "USA physicians")
    for (let id = 1; id <= 200; id++) {
      const fn = firstNames[(id - 1) % firstNames.length];
      const ln = lastNames[(id * 3 - 1) % lastNames.length];

      const spec = specialtyPool[(id * 7) % specialtyPool.length];
      const ac = areaCodes[(id * 5) % areaCodes.length];

      const eventId = id <= 125 ? 15 : 16;
      const eventTag = eventId === 15 ? "event15" : "event16";

      // deterministic phone, email
      const phoneLine = String(1000 + ((id * 37) % 9000)).padStart(4, "0");
      const emailSafeFn = fn.toLowerCase();
      const emailSafeLn = ln.toLowerCase().replace(/[^a-z]/g, "");

      // Uneven distributions (deterministic, no Math.random)
      const physician =
        id <= 125
          ? (id % 5 !== 0)              // ~80% physicians in Event15 bucket
          : (id % 3 === 0);             // ~33% physicians in Event16 bucket

      const checkedIn =
        id <= 125
          ? (id % 7 !== 0)              // ~86% checked in (Event15)
          : (id % 4 === 0 || id % 9 === 0); // ~33–40% checked in (Event16)

      // Only some physicians have NPI (simulates "USA physicians" subset)
      // Keep unique when present; null otherwise.
      const npi =
        physician && (id % 4 === 0)
          ? `NPI${1000000000 + id}`
          : null;

      doctors.push({
        id,
        npi,
        firstName: fn,
        lastName: ln,
        specialty: spec,
        email: `${eventTag}.${emailSafeFn}.${emailSafeLn}.${id}@example.com`,
        phone: `${ac}-555-${phoneLine}`,
        physician,
        checkedIn,
        eventId,
      });
    }

    await Doctor.bulkCreate(doctors);
    console.log(` Doctor seed completed. Inserted ${doctors.length} doctors.`);
  } catch (err) {
    console.error(" Error seeding doctors:", err);
  } finally {
    await db.close();
    process.exit();
  }
}

seedDoctors();